### ISSUE TITLE
Journal Entry

### ISSUE THREAD

**Issue by creative-paramu** [morghim/project-payroll#2]
Sir I have a doubt is journal entry fetch payroll project percentage?
i was working this but i did not have any out put please explain the process.

**Comment by morghim** [comment]
> 

can you give me a screenshot?

**Comment by creative-paramu** [comment]
> 
Sir I upload screenshots of project payroll, salary structure, payroll entry, journal entry
![Screenshot from 2022-11-29 08-59-52](https://user-images.githubusercontent.com/101092028/204431866-788856f6-cd75-44fb-afda-3465e720b1e8.png)
![Screenshot from 2022-11-29 08-58-03](https://user-images.githubusercontent.com/101092028/204431876-4a9c4474-f965-4f83-9ebf-4d51475d9582.png)
![Screenshot from 2022-11-29 08-56-58](https://user-images.githubusercontent.com/101092028/204431879-fb775c6f-079f-40bc-b217-defd3f0db695.png)
![Screenshot from 2022-11-29 08-55-40](https://user-images.githubusercontent.com/101092028/204431883-115b3b27-f6dd-491b-9b4c-561d2b2e8ca1.png)
